blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/aubryio/minotor/discussions
    about: To discuss topics which are not suited for being discussed in issues
